apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: myapp
spec:
  template:
    metadata:
      name: httpd-frontend-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: httpd
        image: httpd:2.4-alpine
  replicas: 3
  selector: 
    matchLabels:
      type: front-end